CREATE TABLE `client`
(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE `user`
(
  id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  client_id BIGINT,
  login VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL
);