/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_inhell_aida_acml_ACML */

#ifndef _Included_ru_inhell_aida_acml_ACML
#define _Included_ru_inhell_aida_acml_ACML
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_inhell_aida_acml_ACML
 * Method:    dgesvd
 * Signature: (Ljava/lang/String;Ljava/lang/String;II[DI[D[DI[DI[DILjava/lang/Integer;)V
 */
JNIEXPORT void JNICALL Java_ru_inhell_aida_acml_ACML_dgesvd
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jdoubleArray, jint, jdoubleArray, jdoubleArray, jint, jdoubleArray, jint, jdoubleArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
