package ru.inheaven.aida.color;

/**
 * @author Anatoly A. Ivanov
 * 31.12.2017 23:00
 */
public class Constant {
    public static final String CMD_CFGTF = "AT+CFGTF\r";
    public static final String CMD_FASSID = "AT+FASSID=str_ssid\r";
    public static final String CMD_HF = "HF-A11ASSISTHREAD";
    public static final String CMD_LANN = "AT+LANN=10.10.10.254,255.255.255.0\r";
    public static final String CMD_OK = "+ok";
    public static final String CMD_Q = "";
    public static final String CMD_RELD = "AT+RELD\r";
    public static final String CMD_W = "AT+W\r";
    public static final String CMD_WAKEY = "AT+WAKEY=WPA2PSK,AES,str_password\r";
    public static final String CMD_WAP = "AT+WAP=11BGN,str_ssid,auto\r";
    public static final String CMD_WMODE_STA = "AT+WMODE=STA\r";
    public static final String CMD_WSCAN = "AT+WSCAN\r";
    public static final String CMD_WSKEY = "AT+WSKEY=str_authentication,str_encryption,str_password\r";
    public static final String CMD_WSSSID = "AT+WSSSID=str_ssid\r";
    public static final String CMD_Z = "AT+Z\r";
    public static final byte[] DATA_CDW_BRIGHTNESS_SEEKBAR;
    public static final byte[] DATA_CIRCLE_CDW;
    public static final byte[] DATA_CIRCLE_DIM;
    public static final byte[] DATA_CIRCLE_RGB;
    public static final byte[] DATA_CURTAIN_OFF = new byte[]{(byte) 2, Byte.MIN_VALUE, (byte) 1};
    public static final byte[] DATA_CURTAIN_ON = new byte[]{(byte) 2, Byte.MIN_VALUE, (byte) 2};
    public static final byte[] DATA_FAN_OFF = new byte[]{(byte) 2, (byte) -125, (byte) 1};
    public static final byte[] DATA_FAN_ON = new byte[]{(byte) 2, (byte) -125, (byte) 2};
    public static final byte[] DATA_FAN_SEEKBAR;
    public static final byte[] DATA_LEARN = new byte[]{(byte) 9, (byte) 55, (byte) 1};
    public static final byte[] DATA_LEARN_ROOM = new byte[]{(byte) 1, (byte) 1, (byte) 1};
    public static final byte[] DATA_OFF = new byte[]{(byte) 2, (byte) 18, (byte) -87};
    public static final byte[] DATA_ON = new byte[]{(byte) 2, (byte) 18, (byte) -85};
    public static final byte[] DATA_RGB_BRIGHTNESS_SEEKBAR;
    public static final byte[] DATA_RGB_B_SEEKBAR;
    public static final byte[] DATA_RGB_G_SEEKBAR;
    public static final byte[] DATA_RGB_LONGCLICK_A1 = new byte[]{(byte) 2, (byte) 2, (byte) -127};
    public static final byte[] DATA_RGB_LONGCLICK_A2 = new byte[]{(byte) 2, (byte) 3, (byte) -124};
    public static final byte[] DATA_RGB_LONGCLICK_A3 = new byte[]{(byte) 2, (byte) 4, (byte) -121};
    public static final byte[] DATA_RGB_LONGCLICK_B1 = new byte[]{(byte) 2, (byte) 2, (byte) -126};
    public static final byte[] DATA_RGB_LONGCLICK_B2 = new byte[]{(byte) 2, (byte) 3, (byte) -123};
    public static final byte[] DATA_RGB_LONGCLICK_B3 = new byte[]{(byte) 2, (byte) 4, (byte) -120};
    public static final byte[] DATA_RGB_MUSIC = new byte[]{(byte) 3, (byte) 80, (byte) 1};
    public static final byte[] DATA_RGB_MUSIC_RECORD_OFF = new byte[]{(byte) 3, (byte) 80, (byte) 2};
    public static final byte[] DATA_RGB_MUSIC_RECORD_ON = new byte[]{(byte) 3, (byte) 80, (byte) 3};
    public static final byte[] DATA_RGB_RUN_OFF;
    public static final byte[] DATA_RGB_RUN_ON = new byte[]{(byte) 2, (byte) 79, (byte) 21};
    public static final byte[] DATA_RGB_RUN_SEEKBAR;
    public static final byte[] DATA_RGB_R_SEEKBAR;
    public static final byte[] DATA_RGB_WHITE_LONGCLICK_OFF = new byte[]{(byte) 2, (byte) 5, (byte) -118};
    public static final byte[] DATA_RGB_WHITE_LONGCLICK_ON = new byte[]{(byte) 2, (byte) 5, (byte) -117};
    public static final byte[] DATA_RGB_WHITE_SEEKBAR;
    public static final byte[] DATA_ROOM1_OFF = new byte[]{(byte) 2, (byte) 10, (byte) -110};
    public static final byte[] DATA_ROOM1_ON = new byte[]{(byte) 2, (byte) 10, (byte) -109};
    public static final byte[] DATA_ROOM2_OFF = new byte[]{(byte) 2, (byte) 10, (byte) -107};
    public static final byte[] DATA_ROOM2_ON = new byte[]{(byte) 2, (byte) 10, (byte) -106};
    public static final byte[] DATA_ROOM3_OFF = new byte[]{(byte) 2, (byte) 10, (byte) -104};
    public static final byte[] DATA_ROOM3_ON = new byte[]{(byte) 2, (byte) 10, (byte) -103};
    public static final byte[] DATA_ROOM4_OFF = new byte[]{(byte) 2, (byte) 10, (byte) -101};
    public static final byte[] DATA_ROOM4_ON = new byte[]{(byte) 2, (byte) 10, (byte) -100};
    public static final byte[] DATA_ROOM5_OFF = new byte[]{(byte) 2, (byte) 10, (byte) -98};
    public static final byte[] DATA_ROOM5_ON = new byte[]{(byte) 2, (byte) 10, (byte) -97};
    public static final byte[] DATA_ROOM6_OFF = new byte[]{(byte) 2, (byte) 10, (byte) -95};
    public static final byte[] DATA_ROOM6_ON = new byte[]{(byte) 2, (byte) 10, (byte) -94};
    public static final byte[] DATA_ROOM7_OFF = new byte[]{(byte) 2, (byte) 10, (byte) -92};
    public static final byte[] DATA_ROOM7_ON = new byte[]{(byte) 2, (byte) 10, (byte) -91};
    public static final byte[] DATA_ROOM8_OFF = new byte[]{(byte) 2, (byte) 10, (byte) -89};
    public static final byte[] DATA_ROOM8_ON = new byte[]{(byte) 2, (byte) 10, (byte) -88};
    public static final byte[] DATA_SAVE1 = new byte[]{(byte) 2, (byte) 10, (byte) -111};
    public static final byte[] DATA_SAVE2 = new byte[]{(byte) 2, (byte) 11, (byte) -108};
    public static final byte[] DATA_SAVE3 = new byte[]{(byte) 2, (byte) 12, (byte) -105};
    public static final byte[] DATA_SAVE4 = new byte[]{(byte) 2, (byte) 13, (byte) -102};
    public static final byte[] DATA_SAVE5 = new byte[]{(byte) 2, (byte) 14, (byte) -99};
    public static final byte[] DATA_SAVE6 = new byte[]{(byte) 2, (byte) 15, (byte) -96};
    public static final byte[] DATA_SAVE7 = new byte[]{(byte) 2, (byte) 16, (byte) -93};
    public static final byte[] DATA_SAVE8 = new byte[]{(byte) 2, (byte) 17, (byte) -90};
    public static final byte[] DATA_SAVE_CLICK = new byte[]{(byte) 2, (byte) 20, (byte) -80};
    public static final byte[] DATA_SAVE_LONGCLICK = new byte[]{(byte) 2, (byte) 20, (byte) -79};
    public static final int DELAY_BETWEEN_TIME = 150;
    public static final int DELAY_CMD_Z = 100;
    public static final int DELAY_HEARTBEAT_TIME = 120000;
    public static final int DELAY_LEARN_TIME = 5000;
    public static final int DELAY_STARTUP = 1500;
    public static final int DELAY_TIME = 30;
    public static final int DELAY_TIME_SCAN = 3000;
    public static final int DOUBLE_TAP_DELAY = 200;
    public static final int MSG_CHANGE_FAIL = 1282;
    public static final int MSG_CHANGE_SUCCESS = 1281;
    public static final int MSG_RESTORE_FAIL = 514;
    public static final int MSG_RESTORE_SUCCESS = 513;
    public static final int MSG_RGB_MUSIC = 1793;
    public static final int MSG_SETTING_ROOM_EDIT = 1537;
    public static final int MSG_SETTING_ROOM_IMG = 1539;
    public static final int MSG_SETTING_ROOM_SAVE = 1538;
    public static final int MSG_SOCKET_CONNECTED = 256;
    public static final int MSG_SOCKET_UNCONNECTED = 257;
    public static final int MSG_STARTUP = 1;
    public static final int MSG_WGC_MUSIC = 1794;
    public static final int MSG_WIFI_CONNECT = 1025;
    public static final int MSG_WIFI_CONNECT_FAIL = 1027;
    public static final int MSG_WIFI_CONNECT_SUCCESS = 1026;
    public static final int MSG_WSCAN_FAIL = 770;
    public static final int MSG_WSCAN_SUCCESS = 769;
    public static final int MSG_WSCAN_TIMEOUT = 771;
    public static final String RECV_MARK = "+ok";
    public static final int REQUESTCODE_ADD_IMG = 5;
    public static final int REQUESTCODE_CROP = 2;
    public static final int REQUESTCODE_IMG = 4;
    public static final int REQUESTCODE_PICK = 1;
    public static final int REQUESTCODE_WIFI = 3;
    public static final int TCP_SEND_PORT = 8899;
    public static final int TCP_TIME_OUT = 3000;
    public static final int TCP_TYPE = 1;
    public static final int TYPE_ROTATEVIEW_CDW = 3;
    public static final int TYPE_ROTATEVIEW_DIM = 4;
    public static final int TYPE_ROTATEVIEW_RGB = 1;
    public static final int TYPE_ROTATEVIEW_WGC = 2;
    public static final int UDP_DATA_SEND_PORT = 8899;
    public static final int UDP_HF_SOTIMEOUT = 50;
    public static final int UDP_RECV_PORT = 48899;
    public static final int UDP_SEND_PORT = 48899;
    public static final int UDP_SOTIMEOUT = 5000;
    public static final int UDP_TYPE = 0;
    public static final int UDP_WSCAN_SOTIMEOUT = 5000;

    static {
        byte[] bArr = new byte[3];
        bArr[0] = (byte) 1;
        bArr[1] = (byte) 1;
        DATA_CIRCLE_RGB = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 54;
        DATA_CIRCLE_CDW = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 56;
        DATA_CIRCLE_DIM = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 35;
        DATA_RGB_BRIGHTNESS_SEEKBAR = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 51;
        DATA_CDW_BRIGHTNESS_SEEKBAR = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 72;
        DATA_RGB_R_SEEKBAR = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 73;
        DATA_RGB_G_SEEKBAR = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 74;
        DATA_RGB_B_SEEKBAR = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 2;
        bArr[1] = (byte) 78;
        DATA_RGB_RUN_OFF = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 34;
        DATA_RGB_RUN_SEEKBAR = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) 75;
        DATA_RGB_WHITE_SEEKBAR = bArr;
        bArr = new byte[3];
        bArr[0] = (byte) 8;
        bArr[1] = (byte) -126;
        DATA_FAN_SEEKBAR = bArr;
    }
}
